name: Publish npm
on:
  push:
    branches:
      - main
      - next
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Verify package
        run: npm run check && npm run pack:dry

      - name: Release and Publish
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
